# Generated by Django 2.2.1 on 2019-05-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divida',
            name='id_cliente',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='divida',
            name='motivo',
            field=models.CharField(max_length=100),
        ),
    ]
